language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121

addons:
  ssh_known_hosts: fettenajs.com

before_deploy:
- openssl aes-256-cbc aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

#before_install:
# - openssl aes-256-cbc -K $encrypted_93abba7592f0_key -iv $encrypted_93abba7592f0_iv
#  -in deploy_rsa.enc -out deploy_rsa -d

script:
 - cd MuscleWeb
 - dotnet restore
 - dotnet publish
 - ssh bp@fettenajs.com
 - ls
 - exit